import type { Template } from '@pdfme/common';
import { BASE_PDF } from '@/lib';

export const getBaseTemplate: Template = {
  basePdf: BASE_PDF,
  schemas: [
    [
      {
        name: 'introduction',
        type: 'text',
        position: {
          x: 20.05,
          y: 77.06,
        },
        width: 169.9,
        height: 44.99,
        alignment: 'center',
        fontSize: 13,
        lineHeight: 1.5,
      },
      {
        name: 'experience',
        type: 'text',
        position: {
          x: 46.64,
          y: 150.14,
        },
        width: 55,
        height: 8,
        fontSize: 15,
        lineHeight: 1,
      },
      {
        name: 'languages',
        type: 'text',
        position: {
          x: 138.54,
          y: 144.02,
        },
        lineHeight: 1.3,
        width: 70,
        height: 13.03,
        fontSize: 12,
      },
      {
        name: 'databases',
        type: 'text',
        position: {
          x: 20,
          y: 191,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'cloud',
        type: 'text',
        position: {
          x: 110,
          y: 191,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'tools',
        type: 'text',
        position: {
          x: 110,
          y: 191,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'backend',
        type: 'text',
        position: {
          x: 20,
          y: 210,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'cicd',
        type: 'text',
        position: {
          x: 110,
          y: 210,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'frontend',
        type: 'text',
        position: {
          x: 20,
          y: 234,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'programming_languages',
        type: 'text',
        position: {
          x: 110,
          y: 234,
        },
        width: 80,
        height: 8,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'architecture',
        type: 'text',
        position: {
          x: 20,
          y: 257,
        },
        width: 80,
        height: 13,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'methodologies',
        type: 'text',
        position: {
          x: 110,
          y: 262,
        },
        width: 80,
        height: 5,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'security',
        type: 'text',
        position: {
          x: 110,
          y: 248,
        },
        width: 80,
        height: 5,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'email_bottom',
        type: 'text',
        position: {
          x: 147,
          y: 284.2,
        },
        width: 41.63,
        height: 5,
        fontSize: 10,
        lineHeight: 1.3,
      },
      {
        name: 'website_bottom',
        type: 'text',
        position: {
          x: 147,
          y: 278.9,
        },
        width: 50,
        height: 5,
        fontSize: 10,
        lineHeight: 1.3,
      },
    ],
  ],
};
