name: Pre-Deployment workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        env:
          EVENT_GITHUB_URL: ${{ secrets.EVENT_GITHUB_URL }}
          EVENT_GITHUB_SOURCE: ${{ secrets.EVENT_GITHUB_SOURCE }}
          PDF_EMAIL: ${{ secrets.PDF_EMAIL }}
          PDF_WEBSITE: ${{ secrets.PDF_WEBSITE }}
          PDF_FILENAME: ${{ secrets.PDF_FILENAME }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests locally
        run: yarn test:coverage --u
